

#ifndef __INCLUDE_OBJ_H__
#define __INCLUDE_OBJ_H__

#if !defined(__cplusplus)
#error C++ compiler required
#endif

#include <objbase.h>

#pragma once


class dmsoft
{
private:
    IDispatch * obj;

public:
    dmsoft();
    virtual ~dmsoft();

    virtual long SetRowGapNoDict(long row_gap);
    virtual long FindPic(long x1,long y1,long x2,long y2,const TCHAR * pic_name,const TCHAR * delta_color,double sim,long dir,long * x,long * y);
    virtual long WriteDataAddrFromBin(long hwnd,LONGLONG addr,long data,long length);
    virtual long BindWindowEx(long hwnd,const TCHAR * display,const TCHAR * mouse,const TCHAR * keypad,const TCHAR * public_desc,long mode);
    virtual long FoobarClose(long hwnd);
    virtual long FoobarFillRect(long hwnd,long x1,long y1,long x2,long y2,const TCHAR * color);
    virtual long FaqCapture(long x1,long y1,long x2,long y2,long quality,long delay,long time);
    virtual long FoobarStartGif(long hwnd,long x,long y,const TCHAR * pic_name,long repeat_limit,long delay);
    virtual long FoobarTextLineGap(long hwnd,long gap);
    virtual CString GetCursorShape();
    virtual CString StringToData(const TCHAR * string_value,long tpe);
    virtual CString ReadIni(const TCHAR * section,const TCHAR * key,const TCHAR * file_name);
    virtual CString FindPicSimMemE(long x1,long y1,long x2,long y2,const TCHAR * pic_info,const TCHAR * delta_color,long sim,long dir);
    virtual long KeyPressChar(const TCHAR * key_str);
    virtual long MoveR(long rx,long ry);
    virtual long FoobarTextRect(long hwnd,long x,long y,long w,long h);
    virtual CString MatchPicName(const TCHAR * pic_name);
    virtual long RightUp();
    virtual long WriteFloatAddr(long hwnd,LONGLONG addr,float v);
    virtual LONGLONG AsmCall(long hwnd,long mode);
    virtual long SendString2(long hwnd,const TCHAR * str);
    virtual long SetExitThread(long en);
    virtual CString FindStrFastS(long x1,long y1,long x2,long y2,const TCHAR * str,const TCHAR * color,double sim,long * x,long * y);
    virtual CString GetDir(long tpe);
    virtual long SetEnumWindowDelay(long delay);
    virtual long FindMulColor(long x1,long y1,long x2,long y2,const TCHAR * color,double sim);
    virtual long FoobarTextPrintDir(long hwnd,long dir);
    virtual long MoveFile(const TCHAR * src_file,const TCHAR * dst_file);
    virtual long AsmClear();
    virtual long WriteDataFromBin(long hwnd,const TCHAR * addr,long data,long length);
    virtual long WaitKey(long key_code,long time_out);
    virtual CString GetDict(long index,long font_index);
    virtual CString FindMultiColorEx(long x1,long y1,long x2,long y2,const TCHAR * first_color,const TCHAR * offset_color,double sim,long dir);
    virtual long MoveDD(long dx,long dy);
    virtual long TerminateProcess(long pid);
    virtual long IsDisplayDead(long x1,long y1,long x2,long y2,long t);
    virtual long EnableGetColorByCapture(long en);
    virtual double ReadDouble(long hwnd,const TCHAR * addr);
    virtual long DeleteFolder(const TCHAR * folder_name);
    virtual long ImageToBmp(const TCHAR * pic_name,const TCHAR * bmp_name);
    virtual long AiYoloSetVersion(const TCHAR * Ver);
    virtual long Stop(long id);
    virtual long GetPointWindow(long x,long y);
    virtual CString EnumIniSectionPwd(const TCHAR * file_name,const TCHAR * pwd);
    virtual CString GetBasePath();
    virtual long CreateFoobarCustom(long hwnd,long x,long y,const TCHAR * pic,const TCHAR * trans_color,double sim);
    virtual long GetScreenDataBmp(long x1,long y1,long x2,long y2,long * data,long * size);
    virtual long SendString(long hwnd,const TCHAR * str);
    virtual CString Md5(const TCHAR * str);
    virtual long SetShowErrorMsg(long show);
    virtual CString FindStrEx(long x1,long y1,long x2,long y2,const TCHAR * str,const TCHAR * color,double sim);
    virtual CString FindMultiColorE(long x1,long y1,long x2,long y2,const TCHAR * first_color,const TCHAR * offset_color,double sim,long dir);
    virtual long SetDisplayRefreshDelay(long t);
    virtual long ActiveInputMethod(long hwnd,const TCHAR * id);
    virtual long EnableRealMouse(long en,long mousedelay,long mousestep);
    virtual long CheckUAC();
    virtual CString GetMachineCode();
    virtual LONGLONG ReadInt(long hwnd,const TCHAR * addr,long tpe);
    virtual CString FindStrWithFontE(long x1,long y1,long x2,long y2,const TCHAR * str,const TCHAR * color,double sim,const TCHAR * font_name,long font_size,long flag);
    virtual long SetWordGapNoDict(long word_gap);
    virtual CString GetNetTime();
    virtual LONGLONG GetModuleBaseAddr(long hwnd,const TCHAR * module_name);
    virtual CString GetCursorShapeEx(long tpe);
    virtual long MiddleClick();
    virtual long SendStringIme2(long hwnd,const TCHAR * str,long mode);
    virtual long DmGuardExtract(const TCHAR * tpe,const TCHAR * path);
    virtual long LoadAiMemory(long addr,long size);
    virtual long WriteStringAddr(long hwnd,LONGLONG addr,long tpe,const TCHAR * v);
    virtual CString FindPicMemEx(long x1,long y1,long x2,long y2,const TCHAR * pic_info,const TCHAR * delta_color,double sim,long dir);
    virtual long SetMinRowGap(long row_gap);
    virtual long IsFileExist(const TCHAR * file_name);
    virtual long DeleteIniPwd(const TCHAR * section,const TCHAR * key,const TCHAR * file_name,const TCHAR * pwd);
    virtual long EncodeFile(const TCHAR * file_name,const TCHAR * pwd);
    virtual CString FindPicSimEx(long x1,long y1,long x2,long y2,const TCHAR * pic_name,const TCHAR * delta_color,long sim,long dir);
    virtual long SetExcludeRegion(long tpe,const TCHAR * info);
    virtual long CheckFontSmooth();
    virtual CString GetMachineCodeNoMac();
    virtual long FindShape(long x1,long y1,long x2,long y2,const TCHAR * offset_color,double sim,long dir,long * x,long * y);
    virtual CString SelectDirectory();
    virtual CString GetWindowTitle(long hwnd);
    virtual CString FetchWord(long x1,long y1,long x2,long y2,const TCHAR * color,const TCHAR * word);
    virtual long GetScreenDepth();
    virtual CString FindShapeE(long x1,long y1,long x2,long y2,const TCHAR * offset_color,double sim,long dir);
    virtual long EnableMouseAccuracy(long en);
    virtual CString AppendPicAddr(const TCHAR * pic_info,long addr,long size);
    virtual long FindPicMem(long x1,long y1,long x2,long y2,const TCHAR * pic_info,const TCHAR * delta_color,double sim,long dir,long * x,long * y);
    virtual CString FindPicMemE(long x1,long y1,long x2,long y2,const TCHAR * pic_info,const TCHAR * delta_color,double sim,long dir);
    virtual long EnableFakeActive(long en);
    virtual long AiYoloFreeModel(long index);
    virtual long DisablePowerSave();
    virtual long MoveWindow(long hwnd,long x,long y);
    virtual long SetDict(long index,const TCHAR * dict_name);
    virtual long WriteInt(long hwnd,const TCHAR * addr,long tpe,LONGLONG v);
    virtual long EnableFontSmooth();
    virtual CString FindStringEx(long hwnd,const TCHAR * addr_range,const TCHAR * string_value,long tpe,long steps,long multi_thread,long mode);
    virtual long EnableSpeedDx(long en);
    virtual long KeyDownChar(const TCHAR * key_str);
    virtual long EnterCri();
    virtual CString EnumWindowByProcess(const TCHAR * process_name,const TCHAR * title,const TCHAR * class_name,long filter);
    virtual CString FindFloat(long hwnd,const TCHAR * addr_range,float float_value_min,float float_value_max);
    virtual CString EnumProcess(const TCHAR * name);
    virtual CString EnumWindow(long parent,const TCHAR * title,const TCHAR * class_name,long filter);
    virtual long FreePic(const TCHAR * pic_name);
    virtual long DelEnv(long index,const TCHAR * name);
    virtual CString RGB2BGR(const TCHAR * rgb_color);
    virtual double ReadDoubleAddr(long hwnd,LONGLONG addr);
    virtual long CaptureJpg(long x1,long y1,long x2,long y2,const TCHAR * file_name,long quality);
    virtual long CreateFoobarEllipse(long hwnd,long x,long y,long w,long h);
    virtual long AiYoloSetModelMemory(long index,long addr,long size,const TCHAR * pwd);
    virtual long SetWindowState(long hwnd,long flag);
    virtual CString EnumWindowByProcessId(long pid,const TCHAR * title,const TCHAR * class_name,long filter);
    virtual long EnableIme(long en);
    virtual long FoobarPrintText(long hwnd,const TCHAR * text,const TCHAR * color);
    virtual long KeyPressStr(const TCHAR * key_str,long delay);
    virtual long SetInputDm(long input_dm,long rx,long ry);
    virtual long ClearDict(long index);
    virtual long VirtualProtectEx(long hwnd,LONGLONG addr,long size,long tpe,long old_protect);
    virtual CString GetColorBGR(long x,long y);
    virtual long CaptureGif(long x1,long y1,long x2,long y2,const TCHAR * file_name,long delay,long time);
    virtual long GetID();
    virtual LONGLONG AsmCallEx(long hwnd,long mode,const TCHAR * base_addr);
    virtual long WriteDouble(long hwnd,const TCHAR * addr,double v);
    virtual CString Hex64(LONGLONG v);
    virtual CString FindColorEx(long x1,long y1,long x2,long y2,const TCHAR * color,double sim,long dir);
    virtual CString ReadIniPwd(const TCHAR * section,const TCHAR * key,const TCHAR * file_name,const TCHAR * pwd);
    virtual CString GetProcessInfo(long pid);
    virtual CString FindStrE(long x1,long y1,long x2,long y2,const TCHAR * str,const TCHAR * color,double sim);
    virtual LONGLONG ReadIntAddr(long hwnd,LONGLONG addr,long tpe);
    virtual CString GetPicSize(const TCHAR * pic_name);
    virtual CString DisAssemble(const TCHAR * asm_code,LONGLONG base_addr,long is_64bit);
    virtual CString EnumIniKey(const TCHAR * section,const TCHAR * file_name);
    virtual long GetFps();
    virtual long GetScreenData(long x1,long y1,long x2,long y2);
    virtual CString DoubleToData(double double_value);
    virtual long WriteIni(const TCHAR * section,const TCHAR * key,const TCHAR * v,const TCHAR * file_name);
    virtual long EnableMouseMsg(long en);
    virtual long SetDictMem(long index,long addr,long size);
    virtual CString ReadStringAddr(long hwnd,LONGLONG addr,long tpe,long length);
    virtual long ScreenToClient(long hwnd,long * x,long * y);
    virtual long FaqGetSize(long handle);
    virtual long CreateFolder(const TCHAR * folder_name);
    virtual long MiddleDown();
    virtual long Capture(long x1,long y1,long x2,long y2,const TCHAR * file_name);
    virtual long GetWindowProcessId(long hwnd);
    virtual CString FindPicS(long x1,long y1,long x2,long y2,const TCHAR * pic_name,const TCHAR * delta_color,double sim,long dir,long * x,long * y);
    virtual long GetColorNum(long x1,long y1,long x2,long y2,const TCHAR * color,double sim);
    virtual long Play(const TCHAR * file_name);
    virtual LONGLONG VirtualAllocEx(long hwnd,LONGLONG addr,long size,long tpe);
    virtual long FindWindowByProcessId(long process_id,const TCHAR * class_name,const TCHAR * title_name);
    virtual CString FindPicExS(long x1,long y1,long x2,long y2,const TCHAR * pic_name,const TCHAR * delta_color,double sim,long dir);
    virtual long FindColor(long x1,long y1,long x2,long y2,const TCHAR * color,double sim,long dir,long * x,long * y);
    virtual long LeftDoubleClick();
    virtual long CopyFile(const TCHAR * src_file,const TCHAR * dst_file,long over);
    virtual long BindWindow(long hwnd,const TCHAR * display,const TCHAR * mouse,const TCHAR * keypad,long mode);
    virtual CString DmGuardParams(const TCHAR * cmd,const TCHAR * sub_cmd,const TCHAR * param);
    virtual long ReadDataToBin(long hwnd,const TCHAR * addr,long length);
    virtual CString Assemble(LONGLONG base_addr,long is_64bit);
    virtual CString FindPicEx(long x1,long y1,long x2,long y2,const TCHAR * pic_name,const TCHAR * delta_color,double sim,long dir);
    virtual long SetUAC(long uac);
    virtual long GetForegroundFocus();
    virtual CString FindPicSimE(long x1,long y1,long x2,long y2,const TCHAR * pic_name,const TCHAR * delta_color,long sim,long dir);
    virtual long FaqCaptureString(const TCHAR * str);
    virtual long SetParam64ToPointer();
    virtual long SetDisplayAcceler(long level);
    virtual CString FindStrExS(long x1,long y1,long x2,long y2,const TCHAR * str,const TCHAR * color,double sim);
    virtual long SetSimMode(long mode);
    virtual CString FindData(long hwnd,const TCHAR * addr_range,const TCHAR * data);
    virtual long GetNowDict();
    virtual long IsFolderExist(const TCHAR * folder);
    virtual long GetResultCount(const TCHAR * str);
    virtual long HackSpeed(double rate);
    virtual long AiYoloDetectObjectsToDataBmp(long x1,long y1,long x2,long y2,float prob,float iou,long * data,long * size,long mode);
    virtual long SetMemoryHwndAsProcessId(long en);
    virtual long FoobarSetFont(long hwnd,const TCHAR * font_name,long size,long flag);
    virtual long ShowScrMsg(long x1,long y1,long x2,long y2,const TCHAR * msg,const TCHAR * color);
    virtual long SetShowAsmErrorMsg(long show);
    virtual CString FindNearestPos(const TCHAR * all_pos,long tpe,long x,long y);
    virtual CString FaqFetch();
    virtual CString ReadFile(const TCHAR * file_name);
    virtual long SetPicPwd(const TCHAR * pwd);
    virtual long FindWindow(const TCHAR * class_name,const TCHAR * title_name);
    virtual long GetWindow(long hwnd,long flag);
    virtual long FoobarClearText(long hwnd);
    virtual long GetMousePointWindow();
    virtual CString FindInt(long hwnd,const TCHAR * addr_range,LONGLONG int_value_min,LONGLONG int_value_max,long tpe);
    virtual long LoadAi(const TCHAR * file_name);
    virtual CString ExcludePos(const TCHAR * all_pos,long tpe,long x1,long y1,long x2,long y2);
    virtual long FreeProcessMemory(long hwnd);
    virtual long ForceUnBindWindow(long hwnd);
    virtual long SetFindPicMultithreadCount(long count);
    virtual long DeleteFile(const TCHAR * file_name);
    virtual long DisableCloseDisplayAndSleep();
    virtual long SaveDict(long index,const TCHAR * file_name);
    virtual long DeleteIni(const TCHAR * section,const TCHAR * key,const TCHAR * file_name);
    virtual long ClientToScreen(long hwnd,long * x,long * y);
    virtual long GetCursorPos(long * x,long * y);
    virtual long LockDisplay(long locks);
    virtual CString FloatToData(float float_value);
    virtual CString GetWindowClass(long hwnd);
    virtual long KeyUpChar(const TCHAR * key_str);
    virtual long FindColorBlock(long x1,long y1,long x2,long y2,const TCHAR * color,double sim,long count,long width,long height,long * x,long * y);
    virtual long EnableKeypadPatch(long en);
    virtual long InitCri();
    virtual long EnableMouseSync(long en,long time_out);
    virtual CString FindPicSimMemEx(long x1,long y1,long x2,long y2,const TCHAR * pic_info,const TCHAR * delta_color,long sim,long dir);
    virtual CString SortPosDistance(const TCHAR * all_pos,long tpe,long x,long y);
    virtual long ExitOs(long tpe);
    virtual CString GetDisplayInfo();
    virtual CString FindStrS(long x1,long y1,long x2,long y2,const TCHAR * str,const TCHAR * color,double sim,long * x,long * y);
    virtual CString OcrEx(long x1,long y1,long x2,long y2,const TCHAR * color,double sim);
    virtual long WriteIniPwd(const TCHAR * section,const TCHAR * key,const TCHAR * v,const TCHAR * file_name,const TCHAR * pwd);
    virtual CString GetCommandLine(long hwnd);
    virtual long KeyUp(long vk);
    virtual long GetFileLength(const TCHAR * file_name);
    virtual CString OcrInFile(long x1,long y1,long x2,long y2,const TCHAR * pic_name,const TCHAR * color,double sim);
    virtual long RunApp(const TCHAR * path,long mode);
    virtual long RightDown();
    virtual long UnBindWindow();
    virtual CString ReadDataAddr(long hwnd,LONGLONG addr,long length);
    virtual CString FindStrFastExS(long x1,long y1,long x2,long y2,const TCHAR * str,const TCHAR * color,double sim);
    virtual long WriteIntAddr(long hwnd,LONGLONG addr,long tpe,LONGLONG v);
    virtual long GetKeyState(long vk);
    virtual CString MoveToEx(long x,long y,long w,long h);
    virtual CString FindPicE(long x1,long y1,long x2,long y2,const TCHAR * pic_name,const TCHAR * delta_color,double sim,long dir);
    virtual long Is64Bit();
    virtual CString GetWordsNoDict(long x1,long y1,long x2,long y2,const TCHAR * color);
    virtual CString FindShapeEx(long x1,long y1,long x2,long y2,const TCHAR * offset_color,double sim,long dir);
    virtual long GetCpuUsage();
    virtual long AsmSetTimeout(long time_out,long param);
    virtual long FindStrFast(long x1,long y1,long x2,long y2,const TCHAR * str,const TCHAR * color,double sim,long * x,long * y);
    virtual long WriteDataAddr(long hwnd,LONGLONG addr,const TCHAR * data);
    virtual long DmGuard(long en,const TCHAR * tpe);
    virtual long DmGuardLoadCustom(const TCHAR * tpe,const TCHAR * path);
    virtual long EnableBind(long en);
    virtual CString ReadString(long hwnd,const TCHAR * addr,long tpe,long length);
    virtual long GetBindWindow();
    virtual long SetDisplayDelay(long t);
    virtual CString SelectFile();
    virtual CString GetNetTimeSafe();
    virtual long UseDict(long index);
    virtual long SetWordLineHeightNoDict(long line_height);
    virtual float ReadFloat(long hwnd,const TCHAR * addr);
    virtual long LoadPicByte(long addr,long size,const TCHAR * name);
    virtual CString FindString(long hwnd,const TCHAR * addr_range,const TCHAR * string_value,long tpe);
    virtual long LoadPic(const TCHAR * pic_name);
    virtual long SetLocale();
    virtual long SpeedNormalGraphic(long en);
    virtual long FaqPost(const TCHAR * server,long handle,long request_type,long time_out);
    virtual long SetScreen(long width,long height,long depth);
    virtual CString FindDouble(long hwnd,const TCHAR * addr_range,double double_value_min,double double_value_max);
    virtual long GetResultPos(const TCHAR * str,long index,long * x,long * y);
    virtual long GetOsBuildNumber();
    virtual CString GetDiskModel(long index);
    virtual CString FindDataEx(long hwnd,const TCHAR * addr_range,const TCHAR * data,long steps,long multi_thread,long mode);
    virtual long EnableShareDict(long en);
    virtual long GetModuleSize(long hwnd,const TCHAR * module_name);
    virtual long WheelUp();
    virtual long DecodeFile(const TCHAR * file_name,const TCHAR * pwd);
    virtual long SendCommand(const TCHAR * cmd);
    virtual long FaqRelease(long handle);
    virtual long SetAero(long en);
    virtual long SendStringIme(const TCHAR * str);
    virtual long GetClientRect(long hwnd,long * x1,long * y1,long * x2,long * y2);
    virtual long EnableKeypadSync(long en,long time_out);
    virtual long CheckInputMethod(long hwnd,const TCHAR * id);
    virtual long SetClientSize(long hwnd,long width,long height);
    virtual CString ReadFileData(const TCHAR * file_name,long start_pos,long end_pos);
    virtual long GetDPI();
    virtual long GetDmCount();
    virtual long ReadDataAddrToBin(long hwnd,LONGLONG addr,long length);
    virtual CString FindStrFastE(long x1,long y1,long x2,long y2,const TCHAR * str,const TCHAR * color,double sim);
    virtual long Log(const TCHAR * info);
    virtual long FoobarSetTrans(long hwnd,long trans,const TCHAR * color,double sim);
    virtual long AsmAdd(const TCHAR * asm_ins);
    virtual long SetFindPicMultithreadLimit(long limit);
    virtual CString Ocr(long x1,long y1,long x2,long y2,const TCHAR * color,double sim);
    virtual long SetWordLineHeight(long line_height);
    virtual long FoobarDrawLine(long hwnd,long x1,long y1,long x2,long y2,const TCHAR * color,long style,long width);
    virtual long StrStr(const TCHAR * s,const TCHAR * str);
    virtual long WriteFloat(long hwnd,const TCHAR * addr,float v);
    virtual CString EnumWindowSuper(const TCHAR * spec1,long flag1,long type1,const TCHAR * spec2,long flag2,long type2,long sort);
    virtual long GetMemoryUsage();
    virtual long SwitchBindWindow(long hwnd);
    virtual CString FindStrFastEx(long x1,long y1,long x2,long y2,const TCHAR * str,const TCHAR * color,double sim);
    virtual CString GetSystemInfo(const TCHAR * tpe,long method);
    virtual long GetLocale();
    virtual long CreateFoobarRoundRect(long hwnd,long x,long y,long w,long h,long rw,long rh);
    virtual long MoveTo(long x,long y);
    virtual long FoobarStopGif(long hwnd,long x,long y,const TCHAR * pic_name);
    virtual CString AiYoloObjectsToString(const TCHAR * objects);
    virtual long SetMouseDelay(const TCHAR * tpe,long delay);
    virtual long SetDisplayInput(const TCHAR * mode);
    virtual CString GetMac();
    virtual CString AiYoloDetectObjects(long x1,long y1,long x2,long y2,float prob,float iou);
    virtual long WriteData(long hwnd,const TCHAR * addr,const TCHAR * data);
    virtual long FindWindowByProcess(const TCHAR * process_name,const TCHAR * class_name,const TCHAR * title_name);
    virtual long FindWindowSuper(const TCHAR * spec1,long flag1,long type1,const TCHAR * spec2,long flag2,long type2);
    virtual long FindWindowEx(long parent,const TCHAR * class_name,const TCHAR * title_name);
    virtual long GetCpuType();
    virtual long FoobarDrawPic(long hwnd,long x,long y,const TCHAR * pic,const TCHAR * trans_color);
    virtual long LeftDown();
    virtual long Reg(const TCHAR * code,const TCHAR * Ver);
    virtual CString EnumIniKeyPwd(const TCHAR * section,const TCHAR * file_name,const TCHAR * pwd);
    virtual long RegEx(const TCHAR * code,const TCHAR * Ver,const TCHAR * ip);
    virtual long OpenProcess(long pid);
    virtual long FaqIsPosted();
    virtual CString GetWords(long x1,long y1,long x2,long y2,const TCHAR * color,double sim);
    virtual long WriteDoubleAddr(long hwnd,LONGLONG addr,double v);
    virtual long SetPath(const TCHAR * path);
    virtual CString Hex32(long v);
    virtual long DownCpu(long tpe,long rate);
    virtual long WriteString(long hwnd,const TCHAR * addr,long tpe,const TCHAR * v);
    virtual long GetWindowRect(long hwnd,long * x1,long * y1,long * x2,long * y2);
    virtual long EnableRealKeypad(long en);
    virtual long GetLastError();
    virtual long GetWindowThreadId(long hwnd);
    virtual long AddDict(long index,const TCHAR * dict_info);
    virtual long GetWindowState(long hwnd,long flag);
    virtual long FoobarSetSave(long hwnd,const TCHAR * file_name,long en,const TCHAR * header);
    virtual long FindPicSim(long x1,long y1,long x2,long y2,const TCHAR * pic_name,const TCHAR * delta_color,long sim,long dir,long * x,long * y);
    virtual CString FindColorBlockEx(long x1,long y1,long x2,long y2,const TCHAR * color,double sim,long count,long width,long height);
    virtual long AiYoloSetModel(long index,const TCHAR * file_name,const TCHAR * pwd);
    virtual long GetTime();
    virtual long SetKeypadDelay(const TCHAR * tpe,long delay);
    virtual long Int64ToInt32(LONGLONG v);
    virtual CString GetAveHSV(long x1,long y1,long x2,long y2);
    virtual CString GetEnv(long index,const TCHAR * name);
    virtual long GetWordResultCount(const TCHAR * str);
    virtual long ReleaseRef();
    virtual long FaqCancel();
    virtual LONGLONG GetRemoteApiAddress(long hwnd,LONGLONG base_addr,const TCHAR * fun_name);
    virtual long SetMouseSpeed(long speed);
    virtual long DownloadFile(const TCHAR * url,const TCHAR * save_file,long timeout);
    virtual CString ExecuteCmd(const TCHAR * cmd,const TCHAR * current_dir,long time_out);
    virtual long DisableScreenSave();
    virtual long Delays(long min_s,long max_s);
    virtual long SetWindowTransparent(long hwnd,long v);
    virtual long GetWordResultPos(const TCHAR * str,long index,long * x,long * y);
    virtual long FoobarUnlock(long hwnd);
    virtual long VirtualFreeEx(long hwnd,LONGLONG addr);
    virtual long FindStr(long x1,long y1,long x2,long y2,const TCHAR * str,const TCHAR * color,double sim,long * x,long * y);
    virtual long EnableFindPicMultithread(long en);
    virtual long GetDictCount(long index);
    virtual long ShowTaskBarIcon(long hwnd,long is_show);
    virtual long EnablePicCache(long en);
    virtual long GetSpecialWindow(long flag);
    virtual long SetEnv(long index,const TCHAR * name,const TCHAR * value);
    virtual long EnableDisplayDebug(long enable_debug);
    virtual CString GetRealPath(const TCHAR * path);
    virtual long WheelDown();
    virtual CString GetColor(long x,long y);
    virtual CString Ver();
    virtual long SetColGapNoDict(long col_gap);
    virtual long CmpColor(long x,long y,const TCHAR * color,double sim);
    virtual CString FindStrWithFontEx(long x1,long y1,long x2,long y2,const TCHAR * str,const TCHAR * color,double sim,const TCHAR * font_name,long font_size,long flag);
    virtual long EnableKeypadMsg(long en);
    virtual CString GetAveRGB(long x1,long y1,long x2,long y2);
    virtual float ReadFloatAddr(long hwnd,LONGLONG addr);
    virtual CString OcrExOne(long x1,long y1,long x2,long y2,const TCHAR * color,double sim);
    virtual CString GetPath();
    virtual long GetScreenWidth();
    virtual long CreateFoobarRect(long hwnd,long x,long y,long w,long h);
    virtual long Beep(long fre,long delay);
    virtual long KeyPress(long vk);
    virtual long SetWindowText(long hwnd,const TCHAR * text);
    virtual long RegExNoMac(const TCHAR * code,const TCHAR * Ver,const TCHAR * ip);
    virtual long LeftUp();
    virtual long SetExportDict(long index,const TCHAR * dict_name);
    virtual long SetClipboard(const TCHAR * data);
    virtual CString GetDiskSerial(long index);
    virtual long FindPicSimMem(long x1,long y1,long x2,long y2,const TCHAR * pic_info,const TCHAR * delta_color,long sim,long dir,long * x,long * y);
    virtual CString IntToData(LONGLONG int_value,long tpe);
    virtual long SetMemoryFindResultToFile(const TCHAR * file_name);
    virtual long GetOsType();
    virtual long GetForegroundWindow();
    virtual long GetMouseSpeed();
    virtual long LeftClick();
    virtual long FindStrWithFont(long x1,long y1,long x2,long y2,const TCHAR * str,const TCHAR * color,double sim,const TCHAR * font_name,long font_size,long flag,long * x,long * y);
    virtual CString FindColorE(long x1,long y1,long x2,long y2,const TCHAR * color,double sim,long dir);
    virtual long SetMinColGap(long col_gap);
    virtual long FindInputMethod(const TCHAR * id);
    virtual long SendPaste(long hwnd);
    virtual long GetScreenHeight();
    virtual long FoobarLock(long hwnd);
    virtual long UnLoadDriver();
    virtual long LeaveCri();
    virtual CString GetDictInfo(const TCHAR * str,const TCHAR * font_name,long font_size,long flag);
    virtual CString FindFloatEx(long hwnd,const TCHAR * addr_range,float float_value_min,float float_value_max,long steps,long multi_thread,long mode);
    virtual CString VirtualQueryEx(long hwnd,LONGLONG addr,long pmbi);
    virtual long GetClientSize(long hwnd,long * width,long * height);
    virtual long AiYoloDetectObjectsToFile(long x1,long y1,long x2,long y2,float prob,float iou,const TCHAR * file_name,long mode);
    virtual long FreeScreenData(long handle);
    virtual long SetDictPwd(const TCHAR * pwd);
    virtual CString AiYoloSortsObjects(const TCHAR * objects,long height);
    virtual long RightClick();
    virtual long WriteFile(const TCHAR * file_name,const TCHAR * content);
    virtual long AiYoloUseModel(long index);
    virtual long RegNoMac(const TCHAR * code,const TCHAR * Ver);
    virtual long DisableFontSmooth();
    virtual CString GetDiskReversion(long index);
    virtual CString FindDoubleEx(long hwnd,const TCHAR * addr_range,double double_value_min,double double_value_max,long steps,long multi_thread,long mode);
    virtual long SetWindowSize(long hwnd,long width,long height);
    virtual long LockMouseRect(long x1,long y1,long x2,long y2);
    virtual long FaqCaptureFromFile(long x1,long y1,long x2,long y2,const TCHAR * file_name,long quality);
    virtual long FindMultiColor(long x1,long y1,long x2,long y2,const TCHAR * first_color,const TCHAR * offset_color,double sim,long dir,long * x,long * y);
    virtual CString BGR2RGB(const TCHAR * bgr_color);
    virtual long KeyDown(long vk);
    virtual CString GetNetTimeByIp(const TCHAR * ip);
    virtual CString GetClipboard();
    virtual CString GetCursorSpot();
    virtual long IsBind(long hwnd);
    virtual CString GetColorHSV(long x,long y);
    virtual long IsSurrpotVt();
    virtual long SetWordGap(long word_gap);
    virtual CString FaqSend(const TCHAR * server,long handle,long request_type,long time_out);
    virtual CString GetWordResultStr(const TCHAR * str,long index);
    virtual long CapturePre(const TCHAR * file_name);
    virtual CString FindIntEx(long hwnd,const TCHAR * addr_range,LONGLONG int_value_min,LONGLONG int_value_max,long tpe,long steps,long multi_thread,long mode);
    virtual long FoobarUpdate(long hwnd);
    virtual long delay(long mis);
    virtual CString GetWindowProcessPath(long hwnd);
    virtual long MiddleUp();
    virtual long LockInput(long locks);
    virtual long CapturePng(long x1,long y1,long x2,long y2,const TCHAR * file_name);
    virtual CString ReadData(long hwnd,const TCHAR * addr,long length);
    virtual CString EnumIniSection(const TCHAR * file_name);
    virtual long FoobarDrawText(long hwnd,long x,long y,long w,long h,const TCHAR * text,const TCHAR * color,long align);
    virtual long SetExactOcr(long exact_ocr);
};


extern dmsoft* g_dm;

#endif
